import Provider from "@/providers/Provider";
import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import React from "react";
import "../globals.css"
import { Toaster } from "@/components/ui/sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vision Board",
  description: "Generated by create next app",
};

function layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="eng">
      <body
        className={` ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>

             {children}
        <Toaster/>
        </Provider>
      </body>
    </html>
  );
}

export default layout;
